export const USERNAME_CHANGED = "USERNAME_CHANGED";

export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const EMAIL_CHANGED = "EMAIL_CHANGED";

export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
