version: "3"
services:
  redis:
    image: redis
    networks: 
      - webnet
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks: 
      - webnet
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_USER: dpranjic
      POSTGRES_DB: slack
    ports:
      - "3030:5432"
  web:
    image: server
    ports:
      - "4001:4001"
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    command: ["./wait-for-it.sh", "-t", "0", "db:5432", "--", "node", "index.js"]
networks:
  webnet: