type Team {
  owner: User!
  members: [User!]!
  channels: [Channel!]!
}

type Mutation {
  createTeam(name: String!): CreateTeamResponse!
}

type CreateTeamResponse {
  ok: Boolean!
  errors: [Error!]
}
