type User {
  id: Int!
  username: String
  email: String!
  teams: [Team!]!
}

type Mutation {
  register(username: String!, email: String!, password: String!): Boolean! #returns user after insert
}

type Query {
  getUser(id: Int!): User! #returns user after insert
  allUsers: [User!]! #returns user after insert
}
