# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

env:
  BRANCH_NAME: echo ${GITHUB_REF##*/}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2 #pulls the code into the container
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2 #tells which node to use
      with:
        node-version: 10.x
    - run: echo ${{env.BRANCH_NAME}}
    - run: npm ci #does clean install of the packages into the ci container
    - run: npm run build --if-present
    - run: npm test
