# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

env:
  BRANCH_NAME: ${GITHUB_REF##*/}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2 #pulls the code into the container
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2 #tells which node to use
      with:
        node-version: 10.x
    - run: ls
    - run: echo ${{env.BRANCH_NAME}}
    - name: Listen to develop branch
      if: ${{ github.ref == 'refs/heads/develop' }}
      env:
          BANANA: "develop"
      run: echo "dev" >> $BANANA
    - name: Listen to master branch
      if: ${{ github.ref == 'refs/heads/master' }}
      env:
          BANANA: "master"
      run: echo "master" 
    - name: Test secret env variable
      run: echo ${{env.BANANA}}
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - run: ls


